/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete.clases;

import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author l34315
 */
public class SPLASH extends javax.swing.JFrame implements Runnable {
    private Thread time = null;
    private BufferedImage IMAGEN;
    private String route;
    private File nombre;
    /**
     * Creates new form SPLASH
     */
    public SPLASH() throws IOException {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        IMAGEN = ImageIO.read(new File("src\\carga3vs.png\\"));
        InsertarImagen(jLabel1, IMAGEN);
        time = new Thread(this);
        time.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void InsertarImagen(JLabel jLabel,BufferedImage IMAGEN) {
        int originalWidth = IMAGEN.getWidth();
        int originalHeight = IMAGEN.getHeight();
        int lblWidth = jLabel.getWidth();
        int lblHeight = jLabel.getHeight();
        int newWidth, newHeight;
        if (originalWidth > originalHeight) {
            newWidth = lblWidth;
            newHeight = (originalHeight * lblWidth) / originalWidth;
        } else {
            newHeight = lblHeight;
            newWidth = (originalWidth * lblHeight) / originalHeight;
        }
        BufferedImage imagenRedimensionada = new BufferedImage(newWidth, newHeight, IMAGEN.getType());
        imagenRedimensionada.getGraphics().drawImage(IMAGEN.getScaledInstance(newWidth, newHeight, java.awt.Image.SCALE_SMOOTH), 0, 0, null);
        jLabel.setIcon(new ImageIcon(imagenRedimensionada));
        jLabel.repaint();
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPLASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SPLASH().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SPLASH.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(time!=null)
        {
            try {
                Thread.sleep(5000);
                this.dispose();
                
            } catch (InterruptedException ex) {
                Logger.getLogger(SPLASH.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        time=null;
        }
        try {
            new BIENVENIDOXD().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SPLASH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}